### ISSUE TITLE
Biography.js

### ISSUE THREAD

**Issue by DmitriiMelnikOnix** [Username2506/Onix-internship#8]
Советую переделать `Biography.js` и перенести переменную `biography` в стейт, в реаке нельзя делать с ней делать то что мы делали когда только начинали изучать js

**Comment by Username2506** [comment]
как-то так, или еще что-то можно в биографии переделать?

**Comment by DmitriiMelnikOnix** [comment]
Лучше создать несколько отдельных стейтов, в одном будет массив из biography, в другим значение highlighting и третий currentItem. Тогда не нужно будет столько распаковок
